#!/usr/bin/env python3
"""Run baseline reproduction jobs at prompt x baseline granularity."""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

from run_pilot import parse_prompt_file


BASELINES = ["negative_prompt", "safree_cogvideox", "videoeraser", "t2vunlearning"]
SELECTABLE_BASELINES = ["clean", *BASELINES]


def parse_gpus(value: str) -> list[int]:
    gpus = [int(part.strip()) for part in value.split(",") if part.strip()]
    if not gpus:
        raise argparse.ArgumentTypeError("--gpus must contain at least one GPU index")
    return gpus


def parse_source_indices(value: str | None, total_prompts: int) -> list[int]:
    if value is None:
        return list(range(total_prompts))
    selected = [int(part.strip()) for part in value.split(",") if part.strip()]
    if not selected:
        raise argparse.ArgumentTypeError("--source-indices must contain at least one index")
    for index in selected:
        if index < 0 or index >= total_prompts:
            raise argparse.ArgumentTypeError(f"source index {index} is outside 0..{total_prompts - 1}")
    return selected


def slot_names(gpus: list[int], slots_per_gpu: int) -> list[tuple[str, int]]:
    slots: list[tuple[str, int]] = []
    for gpu in gpus:
        for slot_index in range(slots_per_gpu):
            slots.append((f"gpu{gpu}_slot{slot_index}", gpu))
    return slots


def shard_prompt_line(prompt: dict[str, str]) -> str:
    return f"{prompt['prompt']} | {prompt['target_concept']} | {prompt['expected_effect']}\n"


def write_prompt_shards(args: argparse.Namespace, prompts: list[dict[str, str]], source_indices: list[int]) -> dict[int, Path]:
    shard_dir = args.output_root / "prompt_shards"
    shard_dir.mkdir(parents=True, exist_ok=True)
    shards: dict[int, Path] = {}
    for source_index in source_indices:
        shard = shard_dir / f"prompt_{source_index:03d}.txt"
        shard.write_text(
            "# One-prompt shard generated by scripts/run_parallel_baseline_jobs.py\n"
            f"# Source prompt file: {args.prompts}\n"
            f"# Source prompt index: {source_index}\n"
            "# Format: <prompt> | <target> | <effect>\n\n"
            + shard_prompt_line(prompts[source_index]),
            encoding="utf-8",
        )
        shards[source_index] = shard
    return shards


def append_common_generation_args(command: list[str], args: argparse.Namespace) -> list[str]:
    command.extend(
        [
            "--model",
            args.model,
            "--seed",
            str(args.seed_for_job),
            "--steps",
            str(args.steps),
            "--guidance-scale",
            str(args.guidance_scale),
            "--num-frames",
            str(args.num_frames),
            "--fps",
            str(args.fps),
            "--height",
            str(args.height),
            "--width",
            str(args.width),
            "--dtype",
            args.dtype,
            "--device",
            "cuda",
        ]
    )
    if args.enable_model_cpu_offload:
        command.append("--enable-model-cpu-offload")
    if args.enable_sequential_cpu_offload:
        command.append("--enable-sequential-cpu-offload")
    if args.vae_slicing:
        command.append("--vae-slicing")
    if args.vae_tiling:
        command.append("--vae-tiling")
    return command


def build_command(baseline: str, args: argparse.Namespace, prompt_shard: Path, output_dir: Path) -> list[str]:
    if baseline == "clean":
        command = [
            sys.executable,
            "scripts/generate_cogvideox_clean.py",
            "--baseline",
            "clean",
            "--prompts",
            str(prompt_shard),
            "--output-dir",
            str(output_dir),
        ]
        return append_common_generation_args(command, args)
    if baseline == "negative_prompt":
        command = [
            sys.executable,
            "scripts/generate_cogvideox_clean.py",
            "--baseline",
            "negative_prompt",
            "--prompts",
            str(prompt_shard),
            "--output-dir",
            str(output_dir),
        ]
        return append_common_generation_args(command, args)
    if baseline == "safree_cogvideox":
        command = [
            sys.executable,
            "scripts/adapters/run_safree_cogvideox.py",
            "--prompts",
            str(prompt_shard),
            "--output-dir",
            str(output_dir),
            "--safree-root",
            str(args.safree_root),
        ]
        return append_common_generation_args(command, args)
    if baseline == "videoeraser":
        command = [
            sys.executable,
            "scripts/adapters/run_videoeraser_cogvideox.py",
            "--mode",
            args.videoeraser_mode,
            "--prompts",
            str(prompt_shard),
            "--output-dir",
            str(output_dir),
            "--videoeraser-root",
            str(args.videoeraser_root),
        ]
        return append_common_generation_args(command, args)
    if baseline == "t2vunlearning":
        command = [
            sys.executable,
            "scripts/adapters/run_t2vunlearning_cogvideox.py",
            "--mode",
            args.t2vunlearning_mode,
            "--prompts",
            str(prompt_shard),
            "--output-dir",
            str(output_dir),
            "--t2vunlearning-root",
            str(args.t2vunlearning_root),
        ]
        return append_common_generation_args(command, args)
    raise ValueError(f"unsupported baseline: {baseline}")


def build_jobs(args: argparse.Namespace) -> list[dict[str, object]]:
    prompts = parse_prompt_file(args.prompts)
    source_indices = parse_source_indices(args.source_indices, len(prompts))
    shards = write_prompt_shards(args, prompts, source_indices)
    slots = slot_names(args.gpus, args.slots_per_gpu)
    selected_baselines = args.baseline or BASELINES
    jobs: list[dict[str, object]] = []
    job_index = 0
    for source_index in source_indices:
        selected_prompt_index = source_indices.index(source_index)
        for baseline in selected_baselines:
            slot_name, gpu = slots[job_index % len(slots)]
            seed = args.seed + source_index
            output_dir = args.output_root / f"{baseline}_shards" / f"prompt_{source_index:03d}"
            run_args = argparse.Namespace(**vars(args))
            run_args.seed_for_job = seed
            job_id = f"{job_index:03d}_{baseline}_prompt_{source_index:03d}"
            jobs.append(
                {
                    "job_id": job_id,
                    "baseline": baseline,
                    "prompt_index": selected_prompt_index,
                    "source_prompt_index": source_index,
                    "target_concept": prompts[source_index]["target_concept"],
                    "expected_effect": prompts[source_index]["expected_effect"],
                    "seed": seed,
                    "slot": slot_name,
                    "gpu": gpu,
                    "prompt_shard": str(shards[source_index]),
                    "output_dir": str(output_dir),
                    "log_path": str(args.output_root / "parallel_logs" / f"{job_id}_gpu{gpu}.log"),
                    "command": build_command(baseline, run_args, shards[source_index], output_dir),
                    "status": "planned",
                }
            )
            job_index += 1
    return jobs


def write_manifest(args: argparse.Namespace, jobs: list[dict[str, object]]) -> Path:
    args.output_root.mkdir(parents=True, exist_ok=True)
    manifest = {
        "created_at_utc": datetime.now(timezone.utc).isoformat(),
        "dry_run": args.dry_run,
        "prompts": str(args.prompts),
        "model": args.model,
        "baselines": args.baseline or BASELINES,
        "gpus": args.gpus,
        "slots_per_gpu": args.slots_per_gpu,
        "max_concurrent_jobs": len(args.gpus) * args.slots_per_gpu,
        "generation": {
            "seed": args.seed,
            "num_inference_steps": args.steps,
            "guidance_scale": args.guidance_scale,
            "num_frames": args.num_frames,
            "fps": args.fps,
            "height": args.height,
            "width": args.width,
            "dtype": args.dtype,
        },
        "jobs": jobs,
    }
    out = args.output_root / "parallel_job_manifest.json"
    out.write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return out


def run_jobs(jobs: list[dict[str, object]], args: argparse.Namespace) -> None:
    args.output_root.joinpath("parallel_logs").mkdir(parents=True, exist_ok=True)
    pending = list(jobs)
    running: dict[str, tuple[dict[str, object], subprocess.Popen, object]] = {}
    available_slots = {slot: gpu for slot, gpu in slot_names(args.gpus, args.slots_per_gpu)}
    failures: list[tuple[str, int]] = []

    while pending or running:
        for slot_name in list(available_slots):
            if not pending:
                break
            job = pending.pop(0)
            gpu = int(available_slots.pop(slot_name))
            job["slot"] = slot_name
            job["gpu"] = gpu
            log_path = Path(str(job["log_path"]))
            log_path.parent.mkdir(parents=True, exist_ok=True)
            log_handle = log_path.open("w", encoding="utf-8")
            env = os.environ.copy()
            env["CUDA_VISIBLE_DEVICES"] = str(gpu)
            env["PYTHONNOUSERSITE"] = "1"
            print(f"Starting {job['job_id']} on {slot_name}")
            job["status"] = "running"
            job["started_at_utc"] = datetime.now(timezone.utc).isoformat()
            process = subprocess.Popen(job["command"], stdout=log_handle, stderr=subprocess.STDOUT, env=env)
            running[slot_name] = (job, process, log_handle)

        time.sleep(args.poll_interval)
        for slot_name, (job, process, log_handle) in list(running.items()):
            return_code = process.poll()
            if return_code is None:
                continue
            log_handle.close()
            running.pop(slot_name)
            available_slots[slot_name] = int(job["gpu"])
            job["finished_at_utc"] = datetime.now(timezone.utc).isoformat()
            job["return_code"] = return_code
            if return_code:
                job["status"] = "failed"
                failures.append((str(job["job_id"]), return_code))
                print(f"Failed {job['job_id']} with exit code {return_code}")
            else:
                job["status"] = "finished"
                print(f"Finished {job['job_id']}")

    if failures:
        details = ", ".join(f"{job_id}={code}" for job_id, code in failures)
        raise SystemExit(f"Parallel baseline job failures: {details}")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__, allow_abbrev=False)
    parser.add_argument("--baseline", action="append", choices=SELECTABLE_BASELINES)
    parser.add_argument("--prompts", type=Path, required=True)
    parser.add_argument("--output-root", type=Path, required=True)
    parser.add_argument("--source-indices")
    parser.add_argument("--model", default="models/CogVideoX-2b")
    parser.add_argument("--safree-root", type=Path, default=Path("baselines/external/SAFREE"))
    parser.add_argument("--videoeraser-root", type=Path, default=Path("baselines/external/VideoEraser"))
    parser.add_argument("--videoeraser-mode", choices=["local", "external", "auto"], default="local")
    parser.add_argument("--t2vunlearning-root", type=Path, default=Path("baselines/external/T2VUnlearning"))
    parser.add_argument("--t2vunlearning-mode", choices=["local", "external", "auto"], default="local")
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--steps", type=int, default=20)
    parser.add_argument("--guidance-scale", type=float, default=6.0)
    parser.add_argument("--num-frames", type=int, default=49)
    parser.add_argument("--fps", type=int, default=8)
    parser.add_argument("--height", type=int, default=480)
    parser.add_argument("--width", type=int, default=720)
    parser.add_argument("--dtype", choices=["fp16", "bf16", "fp32"], default="fp16")
    parser.add_argument("--gpus", type=parse_gpus, default=parse_gpus("0,1,2,3,4,5,6,7"))
    parser.add_argument("--slots-per-gpu", type=int, default=1)
    parser.add_argument("--poll-interval", type=float, default=2.0)
    parser.add_argument("--enable-model-cpu-offload", action="store_true")
    parser.add_argument("--enable-sequential-cpu-offload", action="store_true")
    parser.add_argument("--vae-slicing", action="store_true")
    parser.add_argument("--vae-tiling", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    if args.slots_per_gpu <= 0:
        parser.error("--slots-per-gpu must be positive")
    if args.steps <= 0:
        parser.error("--steps must be positive")
    if args.num_frames <= 0:
        parser.error("--num-frames must be positive")
    if args.fps <= 0:
        parser.error("--fps must be positive")
    if args.height <= 0 or args.width <= 0:
        parser.error("--height and --width must be positive")

    jobs = build_jobs(args)
    manifest = write_manifest(args, jobs)
    print(f"Parallel baseline job manifest written: {manifest}")
    if not args.dry_run:
        run_jobs(jobs, args)
        write_manifest(args, jobs)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
